<<<<<<< HEAD
name: roommate_todo_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11  # Gunakan versi terbaru
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  cupertino_icons: ^1.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/avatar.png
    - assets/fonts/DMSerifText-Regular.ttf

  fonts:
    - family: DMSerifText
      fonts:
        - asset: assets/fonts/DMSerifText-Regular.ttf
=======
name: roommate_todo_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11  # Gunakan versi terbaru
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  cupertino_icons: ^1.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/avatar.png
    - assets/fonts/DMSerifText-Regular.ttf

  fonts:
    - family: DMSerifText
      fonts:
        - asset: assets/fonts/DMSerifText-Regular.ttf
>>>>>>> 18c2103 (first init github)
